"""Crear tabla integration_tokens y campo integration_token_id en audit_logs

Revision ID: 12842db43ba4
Revises: ff23a84faec0
Create Date: 2026-09-05 14:09:31.050444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12842db43ba4'
down_revision: Union[str, None] = 'ff23a84faec0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('token_prefix', sa.String(length=12), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_tokens_organization_id'), 'integration_tokens', ['organization_id'], unique=False)
    op.create_index(op.f('ix_integration_tokens_token_hash'), 'integration_tokens', ['token_hash'], unique=True)
    op.add_column('audit_logs', sa.Column('integration_token_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'audit_logs', 'integration_tokens', ['integration_token_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_column('audit_logs', 'integration_token_id')
    op.drop_index(op.f('ix_integration_tokens_token_hash'), table_name='integration_tokens')
    op.drop_index(op.f('ix_integration_tokens_organization_id'), table_name='integration_tokens')
    op.drop_table('integration_tokens')
    # ### end Alembic commands ###
