"""Crear tablas controls, frameworks, requirements y framework_mappings

Revision ID: 21b164c43fc7
Revises: de4991a11b60
Create Date: 2026-09-05 08:42:14.127127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21b164c43fc7'
down_revision: Union[str, None] = 'de4991a11b60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('controls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('control_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('not_implemented', 'partially_implemented', 'implemented', 'not_applicable', name='control_status'), nullable=False),
    sa.Column('frequency', sa.Enum('continuous', 'daily', 'weekly', 'monthly', 'quarterly', 'semiannual', 'annual', 'ad_hoc', name='control_frequency'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'control_id', name='uq_controls_org_control_id')
    )
    op.create_index(op.f('ix_controls_organization_id'), 'controls', ['organization_id'], unique=False)
    op.create_table('frameworks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='framework_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'short_name', name='uq_frameworks_org_short_name')
    )
    op.create_index(op.f('ix_frameworks_organization_id'), 'frameworks', ['organization_id'], unique=False)
    op.create_table('control_assets',
    sa.Column('control_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('control_id', 'asset_id')
    )
    op.create_table('requirements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('framework_id', sa.Uuid(), nullable=False),
    sa.Column('parent_requirement_id', sa.Uuid(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['framework_id'], ['frameworks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_requirement_id'], ['requirements.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('framework_id', 'code', name='uq_requirements_framework_code')
    )
    op.create_index(op.f('ix_requirements_framework_id'), 'requirements', ['framework_id'], unique=False)
    op.create_index(op.f('ix_requirements_organization_id'), 'requirements', ['organization_id'], unique=False)
    op.create_table('control_requirements',
    sa.Column('control_id', sa.Uuid(), nullable=False),
    sa.Column('requirement_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('control_id', 'requirement_id')
    )
    op.create_table('control_risks',
    sa.Column('control_id', sa.Uuid(), nullable=False),
    sa.Column('risk_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('control_id', 'risk_id')
    )
    op.create_table('framework_mappings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('source_requirement_id', sa.Uuid(), nullable=False),
    sa.Column('target_requirement_id', sa.Uuid(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('source_requirement_id != target_requirement_id', name='ck_framework_mappings_no_self'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_requirement_id', 'target_requirement_id', name='uq_framework_mappings_pair')
    )
    op.create_index(op.f('ix_framework_mappings_organization_id'), 'framework_mappings', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_framework_mappings_organization_id'), table_name='framework_mappings')
    op.drop_table('framework_mappings')
    op.drop_table('control_risks')
    op.drop_table('control_requirements')
    op.drop_index(op.f('ix_requirements_organization_id'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_framework_id'), table_name='requirements')
    op.drop_table('requirements')
    op.drop_table('control_assets')
    op.drop_index(op.f('ix_frameworks_organization_id'), table_name='frameworks')
    op.drop_table('frameworks')
    op.drop_index(op.f('ix_controls_organization_id'), table_name='controls')
    op.drop_table('controls')
    # ### end Alembic commands ###
