"""Crear tablas findings y remediation_actions

Revision ID: 9811736d0a1e
Revises: 381a21bb688e
Create Date: 2026-09-05 12:14:02.504282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '9811736d0a1e'
down_revision: Union[str, None] = '381a21bb688e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('findings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('finding_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('finding_type', sa.Enum('audit_internal', 'audit_external', 'risk_assessment', 'incident', 'control_review', 'compliance', 'vendor', 'other', name='finding_type'), nullable=False),
    # El tipo 'asset_criticality' ya existe (creado por la migración de assets);
    # create_type=False evita que se intente crear de nuevo (mismo caso que
    # 'data_classification' reutilizado en la migración de evidence).
    sa.Column(
        'severity',
        postgresql.ENUM('low', 'medium', 'high', 'critical', name='asset_criticality', create_type=False),
        nullable=False,
    ),
    sa.Column('status', sa.Enum('open', 'under_review', 'remediation', 'pending_validation', 'closed', 'accepted', name='finding_status'), nullable=False),
    sa.Column('source', sa.Enum('audit', 'risk_assessment', 'control', 'compliance', 'incident', 'vendor', 'manual', name='finding_source'), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('discovered_at', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('closed_at', sa.Date(), nullable=True),
    sa.Column('resolution_summary', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'finding_id', name='uq_findings_org_finding_id')
    )
    op.create_index(op.f('ix_findings_organization_id'), 'findings', ['organization_id'], unique=False)
    op.create_table('finding_assets',
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('finding_id', 'asset_id')
    )
    op.create_table('finding_controls',
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('control_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('finding_id', 'control_id')
    )
    op.create_table('finding_evidence',
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('finding_id', 'evidence_id')
    )
    op.create_table('finding_requirements',
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('requirement_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('finding_id', 'requirement_id')
    )
    op.create_table('finding_risks',
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('risk_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('finding_id', 'risk_id')
    )
    op.create_table('remediation_actions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('action_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'blocked', 'completed', 'cancelled', name='action_status'), nullable=False),
    sa.Column(
        'priority',
        postgresql.ENUM('low', 'medium', 'high', 'critical', name='asset_criticality', create_type=False),
        nullable=False,
    ),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('completed_at', sa.Date(), nullable=True),
    sa.Column('completion_notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'action_id', name='uq_remediation_actions_org_action_id')
    )
    op.create_index(op.f('ix_remediation_actions_finding_id'), 'remediation_actions', ['finding_id'], unique=False)
    op.create_index(op.f('ix_remediation_actions_organization_id'), 'remediation_actions', ['organization_id'], unique=False)
    op.create_table('remediation_action_evidences',
    sa.Column('action_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['remediation_actions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('action_id', 'evidence_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('remediation_action_evidences')
    op.drop_index(op.f('ix_remediation_actions_organization_id'), table_name='remediation_actions')
    op.drop_index(op.f('ix_remediation_actions_finding_id'), table_name='remediation_actions')
    op.drop_table('remediation_actions')
    op.drop_table('finding_risks')
    op.drop_table('finding_requirements')
    op.drop_table('finding_evidence')
    op.drop_table('finding_controls')
    op.drop_table('finding_assets')
    op.drop_index(op.f('ix_findings_organization_id'), table_name='findings')
    op.drop_table('findings')
    # ### end Alembic commands ###
