"""Crear tablas assets y risks

Revision ID: de4991a11b60
Revises: 5dc9ab7eacbb
Create Date: 2026-09-04 12:08:22.196292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de4991a11b60'
down_revision: Union[str, None] = '5dc9ab7eacbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('asset_type', sa.Enum('system', 'application', 'server', 'endpoint', 'database', 'service', 'information', 'process', 'vendor', 'other', name='asset_type'), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('criticality', sa.Enum('low', 'medium', 'high', 'critical', name='asset_criticality'), nullable=False),
    sa.Column('data_classification', sa.Enum('public', 'internal', 'confidential', 'restricted', name='data_classification'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'decommissioned', name='asset_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_organization_id'), 'assets', ['organization_id'], unique=False)
    op.create_table('risks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('threat', sa.String(length=255), nullable=False),
    sa.Column('vulnerability', sa.String(length=255), nullable=False),
    sa.Column('likelihood', sa.Integer(), nullable=False),
    sa.Column('impact', sa.Integer(), nullable=False),
    sa.Column('inherent_score', sa.Integer(), nullable=False),
    sa.Column('treatment', sa.Enum('mitigate', 'avoid', 'transfer', 'accept', name='risk_treatment'), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('identified', 'in_evaluation', 'in_treatment', 'accepted', 'closed', name='risk_status'), nullable=False),
    sa.Column('residual_likelihood', sa.Integer(), nullable=True),
    sa.Column('residual_impact', sa.Integer(), nullable=True),
    sa.Column('residual_score', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('impact BETWEEN 1 AND 5', name='ck_risks_impact_range'),
    sa.CheckConstraint('likelihood BETWEEN 1 AND 5', name='ck_risks_likelihood_range'),
    sa.CheckConstraint('residual_impact IS NULL OR residual_impact BETWEEN 1 AND 5', name='ck_risks_residual_impact_range'),
    sa.CheckConstraint('residual_likelihood IS NULL OR residual_likelihood BETWEEN 1 AND 5', name='ck_risks_residual_likelihood_range'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risks_asset_id'), 'risks', ['asset_id'], unique=False)
    op.create_index(op.f('ix_risks_organization_id'), 'risks', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risks_organization_id'), table_name='risks')
    op.drop_index(op.f('ix_risks_asset_id'), table_name='risks')
    op.drop_table('risks')
    op.drop_index(op.f('ix_assets_organization_id'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
