"""Crear tablas vendors y relaciones TPRM

Revision ID: ff23a84faec0
Revises: 9811736d0a1e
Create Date: 2026-09-05 11:22:09.320622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'ff23a84faec0'
down_revision: Union[str, None] = '9811736d0a1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('vendor_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('criticality', postgresql.ENUM('low', 'medium', 'high', 'critical', name='asset_criticality', create_type=False), nullable=False),
    sa.Column('data_classification', postgresql.ENUM('public', 'internal', 'confidential', 'restricted', name='data_classification', create_type=False), nullable=False),
    sa.Column('status', sa.Enum('prospect', 'active', 'suspended', 'terminated', name='vendor_status'), nullable=False),
    sa.Column('due_diligence_status', sa.Enum('pending', 'in_review', 'approved', 'approved_with_conditions', 'rejected', 'expired', name='vendor_due_diligence_status'), nullable=False),
    sa.Column('relationship_start_date', sa.Date(), nullable=False),
    sa.Column('contract_end_date', sa.Date(), nullable=True),
    sa.Column('last_security_review_date', sa.Date(), nullable=True),
    sa.Column('next_security_review_date', sa.Date(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'vendor_id', name='uq_vendors_org_vendor_id')
    )
    op.create_index(op.f('ix_vendors_organization_id'), 'vendors', ['organization_id'], unique=False)
    op.create_table('vendor_evidence',
    sa.Column('vendor_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vendor_id', 'evidence_id')
    )
    op.create_table('vendor_findings',
    sa.Column('vendor_id', sa.Uuid(), nullable=False),
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vendor_id', 'finding_id')
    )
    op.create_table('vendor_risks',
    sa.Column('vendor_id', sa.Uuid(), nullable=False),
    sa.Column('risk_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vendor_id', 'risk_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor_risks')
    op.drop_table('vendor_findings')
    op.drop_table('vendor_evidence')
    op.drop_index(op.f('ix_vendors_organization_id'), table_name='vendors')
    op.drop_table('vendors')
    # ### end Alembic commands ###
